import type { Metadata } from "next";

import "./globals.css";
import { WalletProvider } from "@/providers/WalletProvider";
import { StarknetProvider } from "@/providers/StarknetProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Starfield from "@/components/Starfield";

export const metadata: Metadata = {
  title: "StarkDevs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-transparent flex flex-col justify-start items-center text-white h-screen">
        <StarknetProvider>
          <WalletProvider>{children}</WalletProvider>
        </StarknetProvider>
        <ToastContainer
          position="top-center"
          autoClose={2500}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Starfield
          starCount={1000}
          starColor={[232, 255, 251]}
          speedFactor={0.05}
          backgroundColor="#0c0d10"
        />
      </body>
    </html>
  );
}
